// The bridge between `src/problems/<id>/doc.ts` and the learn page.
//
// Owns: which problems have a typed teaching document, and fetching one. Owns
// no markup (`components/teaching-doc.tsx` renders it) and no policy about who
// may read one (`problem-detail.tsx` applies the ledger cap).
//
// It used to own a third thing and no longer does: `composeLearnPage` turned
// the document back into one Markdown STRING for the parser to re-read. The
// document is rendered as what it is now, so the round trip — and the flatten
// of every typed table to pipe-delimited text — is gone with it.
//
// LAZY, and this is the whole reason the glob is here rather than an import.
// A content module is ~40 KB of prose and there will be 127 of them. Vite gives
// every match its own chunk and the KEYS without reading a byte, so `hasContent`
// costs nothing and `loadContent` costs one fetch — the same bargain
// `learn-pages.ts` struck with `docs/learn/*.md`, and the reason the first
// chunk did not grow when this landed.
//
// WHY THIS REPLACES `docs/learn/<id>.md`. That file was generated by splicing a
// Markdown teaching document into data pulled from the problem record, which
// meant a problem's content lived in two files in two formats with a 482-line
// generator between them. Three bugs in one day came out of that arrangement:
// 45 of 82 documents taught approaches the record had no entry for, a journey
// act was wired to `alternatives` by array INDEX and silently repointed, and
// `docs/learn` itself was 69% a byte-for-byte copy. Here the document is one
// typed object beside the record it teaches, and the page is composed at read
// time from both — so there is no third artifact to keep in step.

import type { TeachingDoc } from "@/content/types"

// `doc.ts` and nothing else. A problem directory holds BOTH halves — the record
// (`index.ts`, eager, on the static chain from `data/index.ts`) and the teaching
// document (`doc.ts`, lazy, only ever reached from here). Globbing the directory
// instead would match the record too and put 30 KB of prose per problem into
// the first chunk, which is the exact thing B95 is about.
const MODULES = import.meta.glob("/src/problems/*/doc.ts", {
  import: "doc",
}) as Record<string, () => Promise<TeachingDoc>>

const byId = new Map<string, () => Promise<TeachingDoc>>(
  Object.entries(MODULES).map(([path, load]) => [
    path.replace(/^.*\/([^/]+)\/doc\.ts$/, "$1"),
    load,
  ])
)

export const hasContent = (id: string) => byId.has(id)

/** how many problems carry a typed document — quoted by the UI so it cannot drift */
export const contentCount = byId.size

export async function loadContent(id: string): Promise<TeachingDoc | undefined> {
  const load = byId.get(id)
  return load ? await load() : undefined
}
