// The bridge between `src/problems/<id>/doc.ts` and the learn page.
//
// Owns: which problems have a typed teaching document, fetching one, and
// composing it back into the page's block order. Owns no markup
// (`components/markdown.tsx`) and no policy about who may read one
// (`problem-detail.tsx` applies the ledger cap).
//
// LAZY, and this is the whole reason the glob is here rather than an import.
// A content module is ~40 KB of prose and there will be 127 of them. Vite gives
// every match its own chunk and the KEYS without reading a byte, so `hasContent`
// costs nothing and `loadContent` costs one fetch — the same bargain
// `learn-pages.ts` struck with `docs/learn/*.md`, and the reason the first
// chunk did not grow when this landed.
//
// WHY THIS REPLACES `docs/learn/<id>.md`. That file was generated by splicing a
// Markdown teaching document into data pulled from the problem record, which
// meant a problem's content lived in two files in two formats with a 482-line
// generator between them. Three bugs in one day came out of that arrangement:
// 45 of 82 documents taught approaches the record had no entry for, a journey
// act was wired to `alternatives` by array INDEX and silently repointed, and
// `docs/learn` itself was 69% a byte-for-byte copy. Here the document is one
// typed object beside the record it teaches, and the page is composed at read
// time from both — so there is no third artifact to keep in step.

import type { Problem } from "@/data"
import type { TeachingDoc } from "@/content/types"
import type { Rung } from "@/lib/ladder"

// `doc.ts` and nothing else. A problem directory holds BOTH halves — the record
// (`index.ts`, eager, on the static chain from `data/index.ts`) and the teaching
// document (`doc.ts`, lazy, only ever reached from here). Globbing the directory
// instead would match the record too and put 30 KB of prose per problem into
// the first chunk, which is the exact thing B95 is about.
const MODULES = import.meta.glob("/src/problems/*/doc.ts", {
  import: "doc",
}) as Record<string, () => Promise<TeachingDoc>>

const byId = new Map<string, () => Promise<TeachingDoc>>(
  Object.entries(MODULES).map(([path, load]) => [
    path.replace(/^.*\/([^/]+)\/doc\.ts$/, "$1"),
    load,
  ])
)

export const hasContent = (id: string) => byId.has(id)

/** how many problems carry a typed document — quoted by the UI so it cannot drift */
export const contentCount = byId.size

export async function loadContent(id: string): Promise<TeachingDoc | undefined> {
  const load = byId.get(id)
  return load ? await load() : undefined
}

const fence = (code: string, lang = "python") =>
  "```" + lang + "\n" + code + "\n```"

const pipeTable = (head: string[], rows: string[][]) =>
  [
    `| ${head.join(" | ")} |`,
    `|${head.map(() => "---").join("|")}|`,
    ...rows.map((r) => `| ${r.join(" | ")} |`),
  ].join("\n")

/**
 * The page, in the order a reader meets it: what the problem is, then what its
 * input promises, then every approach in full, then the arc that joins them,
 * then the ladder in three languages, then the script.
 *
 * Composed rather than stored. The data half comes from the record the app
 * already has in memory; the teaching half from the document. Neither is
 * copied, so neither can drift from the other — which is the entire point of
 * the exercise and the reason `scripts/gen-learn.mjs` is no longer needed for
 * a problem that has one of these.
 */
export function composeLearnPage(
  problem: Problem,
  doc: TeachingDoc,
  rungs: Rung[]
): string {
  const out: string[] = []
  const h = (level: number, text: string) => out.push(`${"#".repeat(level)} ${text}`)

  h(1, problem.title)
  out.push(problem.statement)

  h(2, "What the input promises")
  out.push(problem.constraints.map((c) => `- ${c}`).join("\n"))

  h(2, "Examples")
  out.push(
    pipeTable(
      ["in", "out", ""],
      problem.examples.map((e) => [e.input, e.output, e.note ?? ""])
    )
  )

  h(2, "Understanding the Problem")
  out.push(doc.understanding)

  if (doc.unlocks?.length) {
    h(3, "The constraints, and what each one unlocks")
    out.push(
      pipeTable(
        ["Constraint", "What it forces or permits"],
        doc.unlocks.map((u) => [u.constraint, u.what])
      )
    )
  }

  // The document's own numbered failure list, straight after the constraints
  // that make each one possible — and before the first approach, because every
  // approach's "Common mistake" cites these by number.
  if (doc.traps) {
    h(2, "The failure modes — the whole test suite")
    out.push(doc.traps.intro)
    out.push(
      pipeTable(
        ["#", "Failure", "Example", "What the code must check"],
        doc.traps.rows.map((t, i) => [`**${i + 1}**`, t.name, t.example, t.check])
      )
    )
    if (doc.traps.outro) out.push(doc.traps.outro)
  }

  if (doc.calculations) {
    h(2, "Reading the Calculations")
    out.push(doc.calculations)
  }

  doc.approaches.forEach((a, i) => {
    h(2, `Approach ${i + 1}: ${a.title}`)
    h(3, "The idea")
    out.push(a.idea)
    h(3, "How to think about it")
    out.push(a.intuition)
    h(3, "Worked example")
    out.push(a.worked)
    h(3, "Code")
    out.push(fence(a.code))
    if (a.codeNote) out.push(a.codeNote)
    h(3, "Common mistake")
    out.push(a.mistake)
    h(3, "Complexity and when to use this")
    out.push(a.cost)
    // the parts the six named ones do not cover, in the order the author wrote
    // them: the `> **Why it works.**` argument the format demands of every
    // greedy and every two-pointer solution, and the cost-of-mutation notes
    for (const n of a.notes ?? []) {
      h(3, n.title)
      out.push(n.body)
    }
  })

  h(2, "The Overall Arc")
  out.push(doc.arc)

  if (doc.comparison.rows.length) {
    h(2, "Comparison")
    out.push(pipeTable(doc.comparison.head, doc.comparison.rows))
  }

  h(2, "Interview Priority")
  out.push(doc.interview)

  if (doc.fluent) {
    h(2, "How to Get Fluent")
    out.push(doc.fluent)
  }

  // The ladder in three languages, from the RECORD — the one part of this page
  // that was never prose. A document that disagreed with it is the gap B79
  // closed; now the two cannot disagree, because only one of them exists.
  if (rungs.length) {
    h(2, "The same ladder, in Python, Java and C++")
    out.push(
      "Every rung the problem page shows, with the translations the compile gate checks."
    )
    rungs.forEach((r, i) => {
      h(2, `Rung ${i + 1} — ${r.name}`)
      out.push(`\`${r.cost}\``)
      out.push(r.idea)
      out.push(fence(r.code.python))
      if (r.code.java) out.push(fence(r.code.java, "java"))
      if (r.code.cpp) out.push(fence(r.code.cpp, "cpp"))
    })
  }

  h(2, "Full Runnable Script")
  out.push(
    "Every approach above, plus a differential test over random inputs. This is the script `scripts/verify-deep.mjs` executes on every pull request — and the one the Run button below runs in your browser."
  )
  // the author's note on the script: which helpers are scaffolding, and the
  // guards the harness needs. Its own field because the first conversion
  // dropped it and the round-trip check found it (`scriptNote`).
  if (doc.scriptNote) out.push(doc.scriptNote)
  out.push(fence(doc.script))
  if (doc.scriptOutput) {
    h(3, "Output when run")
    out.push(doc.scriptOutput)
  }

  // anything the house format carries that has no field of its own — a section
  // naming the sibling problems that use the same move, an aside under the
  // comparison table. Kept in document order rather than dropped.
  for (const n of doc.notes ?? []) {
    h(2, n.title)
    out.push(n.body)
  }

  return out.join("\n\n") + "\n"
}
