// What a problem page still owes its reader.
//
// Every band of the problem page degrades to nothing when its field is absent,
// which is what lets 152 thin pages render rather than break — and is also how
// a gap becomes invisible. A missing `checks` band does not look missing; it
// looks like a page that was designed without one. So the gap is SAID, at the
// foot of the page, in the reader's language and with the same words the
// authoring ledger uses.
//
// One function, two consumers, so they cannot drift:
//   * the page's own band (`components/problem-debt.tsx`)
//   * `docs/PAGE-BACKLOG.md`, generated by `scripts/page-backlog.mjs`
//
// Plain `.ts` and DOM-free on purpose: a node test and a build script both
// load it (the trap in `CLAUDE.md` — a rule that must fail the build cannot
// live in a `.tsx`).
import type { Problem } from "@/data/types.ts"

/** one thing a page is missing, said once, in the reader's language */
export interface Debt {
  /** stable id, used by the ledger's columns and by the tests */
  id:
    | "journey"
    | "unlocks"
    | "figures"
    | "checks"
    | "cost-why"
    | "rung-cost-why"
    | "reading"
    | "arc"
    | "explanation"
  /** what is missing, as a reader would say it */
  label: string
  /** what the reader loses by its absence — never a scolding of the author */
  cost: string
  /** the backlog item that tracks it, for the ledger */
  item: string
}

/**
 * What this page owes, worst first.
 *
 * `has` carries the two facts the record itself cannot answer: whether a
 * journey exists for this problem, and whether a teaching document does. Both
 * live in manifests the caller already holds, and passing them keeps this
 * module loadable with no data at all.
 */
export function debtsOf(
  problem: Problem,
  has: { journey: boolean; explanation: boolean }
): Debt[] {
  const out: Debt[] = []
  const rungs = problem.alternatives ?? []

  if (!has.journey)
    out.push({
      id: "journey",
      label: "a journey",
      cost: "this problem is a static walkthrough — you watch it rather than earn it",
      item: "B67",
    })

  if (!has.explanation)
    out.push({
      id: "explanation",
      label: "the long explanation",
      cost: "the page ends at the ladder; there is no essay under it yet",
      item: "B70",
    })

  if (!problem.unlocks?.length)
    out.push({
      id: "unlocks",
      label: "what each bound buys",
      cost: "the constraints are listed but not read — a bound is noise until it rules something out",
      item: "B104",
    })
  else if (!problem.unlocks.some((u) => u.figure))
    out.push({
      id: "figures",
      label: "a bound drawn",
      cost: "the numbers are stated, not felt",
      item: "B104",
    })

  if (!problem.checks?.length)
    out.push({
      id: "checks",
      label: "read-before-you-solve questions",
      cost: "nothing on the page asks whether you understood the statement before the hints start giving it away",
      item: "B104",
    })

  if (!problem.costWhy)
    out.push({
      id: "cost-why",
      label: "how the target bound was counted",
      cost: "the page asserts a complexity instead of deriving it",
      item: "B104",
    })
  else if (rungs.length > 0 && !rungs.every((a) => a.costWhy))
    out.push({
      id: "rung-cost-why",
      label: "the count behind every rung's bound",
      cost: `${rungs.filter((a) => !a.costWhy).length} of ${rungs.length} rungs state a bound without showing the count`,
      item: "B104",
    })

  if (!problem.arc)
    out.push({
      id: "arc",
      label: "the closing idea",
      cost: "nothing says what the whole ladder had in common — the part you carry to the next problem",
      item: "B104",
    })

  if (!problem.reading?.length)
    out.push({
      id: "reading",
      label: "sources for this problem",
      cost: "the reading list falls back to the pattern's, which is about the technique rather than this instance",
      item: "B104",
    })

  return out
}

/** every debt id, in the order `debtsOf` can emit them — the ledger's columns */
export const DEBT_IDS: Debt["id"][] = [
  "journey",
  "explanation",
  "unlocks",
  "figures",
  "checks",
  "cost-why",
  "rung-cost-why",
  "arc",
  "reading",
]
