// Emit `src/data/demos.ts` — one Python argument list per problem, so the Run
// button on a code block can actually print something.
//
// THE PROBLEM THIS SOLVES, measured in a real browser on 2026-09-15. Every
// ```python fence in a teaching document is a function DEFINITION: no `print`,
// no top-level call. Pressing Run on `balanced-brackets` gave "exit 0 · 5 ms"
// and "the script printed nothing" — three of the four buttons on that page did
// nothing a reader could see. Only the full script at the foot, which has its
// own `main()`, printed anything at all.
//
// A definition has nothing to print. So the Run button appends a call, and this
// file is where the argument comes from: `scripts/localsmith/vectors.mjs`, the
// same inputs the differential runner drives Java and C++ with. They are
// already known to work against the Python, which is the whole reason to use
// them rather than parse an example out of prose.
//
// A linked list or a tree is built with the same `__mklist` / `__mktree` the
// driver uses — they ride along in `src/lib/py-preamble.ts`, copied verbatim
// from that file — so those problems get a one-line call too. A `shape: "class"`
// problem does not: its entry point is a class to instantiate against a script
// of operations, which is a different driver and not one line.
//
// GENERATED, committed, and guarded: `src/data/demos.test.ts` rebuilds it in
// memory and fails if the checked-in copy has drifted.
//
// Run:  node scripts/gen-demos.mjs
//       node scripts/gen-demos.mjs --check   # exit 1 if stale, writes nothing

import { readFileSync, writeFileSync } from "node:fs"
import { VECTORS } from "./localsmith/vectors.mjs"

const check = process.argv.includes("--check")
const OUT = "src/data/demos.ts"

/** the parameter types this can render as a Python literal with no scaffolding */
const SIMPLE = new Set([
  "int",
  "float",
  "bool",
  "string",
  "int[]",
  "string[]",
  "int[][]",
  "char[]",
])

/** a JS value as Python source. JSON is Python for everything here except the
 *  three literals it spells differently. */
const py = (v) =>
  JSON.stringify(v)
    .replace(/\btrue\b/g, "True")
    .replace(/\bfalse\b/g, "False")
    .replace(/\bnull\b/g, "None")

/** a linked-list argument is a row of values, or {list, cycle} when the tail
 *  points back — cycle-detect's input is a SHAPE rather than a value */
const listArg = (v) =>
  Array.isArray(v)
    ? `__mklist(${py(v)})`
    : `__mklist(${py(v.list)}, ${v.cycle ?? -1})`

const arg = (v, t) =>
  t === "list" ? listArg(v) : t === "tree" ? `__mktree(${py(v)})` : py(v)

const demos = {}
for (const [id, spec] of Object.entries(VECTORS)) {
  // `shape: "class"` means the entry point is a class to instantiate against a
  // script of operations — a different driver, and not one appended line.
  if (spec.shape) continue
  if (!spec.params.every((t) => SIMPLE.has(t) || t === "list" || t === "tree"))
    continue
  const first = spec.cases?.[0]
  if (!first) continue
  demos[id] = first.map((v, i) => arg(v, spec.params[i])).join(", ")
}

const body = `// GENERATED by scripts/gen-demos.mjs — do not edit.
//
// One Python argument list per problem: the first case from
// \`scripts/localsmith/vectors.mjs\`, which is the same input the differential
// runner drives every Java and C++ block with.
//
// The Run button on a code block appends \`print(<entry>(<these args>))\` when
// the block defines a function and calls nothing — which is every approach
// fence in every teaching document. Without it, Run defines a function and
// reports "the script printed nothing".
//
// ${Object.keys(demos).length} of ${Object.keys(VECTORS).length} problems are here. A linked list or a tree is built with the
// \`__mklist\` / \`__mktree\` that ride along in \`src/lib/py-preamble.ts\`. The
// rest are \`shape: "class"\` — a class to instantiate against a script of
// operations, which is not one appended line — and those blocks say so.
//
// \`src/data/demos.test.ts\` rebuilds this in memory and fails if it has drifted.

export const DEMOS: Record<string, string> = {
${Object.entries(demos)
  .map(([id, args]) => `  ${JSON.stringify(id)}: ${JSON.stringify(args)},`)
  .join("\n")}
}
`

if (check) {
  const lf = (s) => s.replace(/\r\n/g, "\n")
  let have = ""
  try {
    have = readFileSync(OUT, "utf8")
  } catch {
    /* absent counts as stale */
  }
  const stale = lf(have) !== lf(body)
  console.log(
    stale ? `${OUT} is stale — run node scripts/gen-demos.mjs` : `ok     ${OUT}`
  )
  process.exitCode = stale ? 1 : 0
} else {
  writeFileSync(OUT, body, "utf8")
  console.log(
    `wrote ${OUT}: ${Object.keys(demos).length} of ${Object.keys(VECTORS).length} problems can be called in one line`
  )
}
