// What is MISSING from each problem's page, counted rather than remembered.
//
// `docs/learn/<id>.md` is generated, so its shape is guaranteed. What is not
// guaranteed is the authored half: whether a problem has a teaching document at
// all, and whether that document carries the sections `docs/deep/README.md`
// requires. Two of those sections are recent — "Reading the Calculations" and
// "How to Get Fluent" were added on 2026-09-13 after a reader said they could
// follow the prose and then stalled at the arithmetic — so almost every older
// document is missing them, and the only useful form of that fact is a list.
//
// It also catches drift the runnable-script gate structurally cannot see:
// `verify-deep.mjs` runs the script and checks the approaches agree with each
// other, which says nothing about whether the document's ladder still matches
// the app's. A document may add rungs; the spec requires it to say so.
//
// Run:  node scripts/learn-gaps.mjs             # the table, and write the doc
//       node scripts/learn-gaps.mjs --quiet     # just the summary line
//       node scripts/learn-gaps.mjs --strict    # exit 1 on undisclosed drift

import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { PATTERNS, PROBLEMS } from "../src/data/index.ts"

const strict = process.argv.includes("--strict")
const quiet = process.argv.includes("--quiet")
const DEEP = "docs/deep"
const REPORT = "docs/LEARN-GAPS.md"

// "an addition", "not in the data file", "(an addition — …)" all count: the
// spec asks for the fact to be stated, not for one exact phrasing
const DISCLOSES = /\ban addition\b|not in the data file|beyond the app's ladder|addition to the app/i

/** Each required section, and how to see it. Named for what a READER loses
 *  when it is missing, because that is the argument for writing it. */
const SECTIONS = [
  {
    key: "calculations",
    heading: "Reading the Calculations",
    test: (md) => /^## Reading the Calculations/m.test(md),
    lost: "no symbol table: a reader who stalls at `j = index_of.get(target - x, -1)` has nowhere to go",
  },
  {
    key: "fluent",
    heading: "How to Get Fluent",
    test: (md) => /^## How to Get Fluent/m.test(md),
    lost: "no drills: the page can be read and still not be practised",
  },
  {
    key: "hood",
    heading: "Under the hood",
    test: (md) => /^> \*\*Under the hood\.\*\*/m.test(md),
    lost: "a cost is taken on faith — what the language actually does is never shown",
  },
  {
    key: "interview",
    heading: "Interview Priority",
    test: (md) => /^## Interview Priority/m.test(md),
    lost: "no guidance on which approaches to know cold",
  },
  {
    key: "arc",
    heading: "The Overall Arc",
    test: (md) => /^## The Overall Arc/m.test(md),
    lost: "the rungs never join into one story",
  },
  {
    key: "comparison",
    heading: "Comparison",
    test: (md) => /^## Comparison/m.test(md),
    lost: "no side-by-side of the trade-offs",
  },
]

export function audit() {
  const have = new Set(
    readdirSync(DEEP)
      .filter((f) => f.endsWith("_explained.md"))
      .map((f) => f.replace(/_explained\.md$/, ""))
  )

  return PROBLEMS.map((problem) => {
    if (!have.has(problem.id)) {
      return { problem, taught: false, missing: SECTIONS.map((s) => s.key), extra: 0 }
    }
    const md = readFileSync(join(DEEP, `${problem.id}_explained.md`), "utf8").replace(
      /\r\n/g,
      "\n"
    )
    const approaches = [...md.matchAll(/^## Approach\b[^\n]*/gm)].length
    const dataRungs = (problem.alternatives?.length ?? 0) + 1
    return {
      problem,
      taught: true,
      missing: SECTIONS.filter((s) => !s.test(md)).map((s) => s.key),
      extra: approaches - dataRungs,
      disclosed: DISCLOSES.test(md),
      words: md.split(/\s+/).length,
    }
  })
}

function report(rows) {
  const untaught = rows.filter((r) => !r.taught)
  const undisclosed = rows.filter((r) => r.taught && r.extra > 0 && !r.disclosed)
  const perSection = SECTIONS.map((s) => ({
    ...s,
    missing: rows.filter((r) => r.missing.includes(s.key)),
  }))

  const lines = [
    `# What is missing from each problem's page`,
    ``,
    `<!-- Generated by scripts/learn-gaps.mjs. Run it again rather than editing. -->`,
    ``,
    `Every problem has a page at [\`docs/learn/<id>.md\`](learn/) — that half is generated`,
    `and cannot be missing. This is the state of the **authored** half: the teaching`,
    `document in \`docs/deep/\`, and the sections [its spec](deep/README.md) requires.`,
    ``,
    `**${rows.length - untaught.length} of ${rows.length} problems have a teaching document.**`,
    ``,
    `## The gap, by section`,
    ``,
    `| Section | Have it | Missing | What a reader loses without it |`,
    `|---|---|---|---|`,
    ...perSection.map(
      (s) =>
        `| ${s.heading} | ${rows.length - s.missing.length} | **${s.missing.length}** | ${s.lost} |`
    ),
    ``,
    `## Problems with no teaching document at all — ${untaught.length}`,
    ``,
    ...(untaught.length
      ? PATTERNS.flatMap((pattern) => {
          const mine = untaught.filter((r) => r.problem.pattern === pattern.id)
          return mine.length
            ? [`- **${pattern.name}** (${mine.length}): ${mine.map((r) => r.problem.id).join(", ")}`]
            : []
        })
      : [`None.`]),
    ``,
    `## Documents that add approaches without saying so — ${undisclosed.length}`,
    ``,
    `\`docs/deep/README.md\` allows a document to teach a rung the data file lacks, and`,
    `requires it to say that it is an addition. These do not:`,
    ``,
    ...(undisclosed.length
      ? undisclosed.map(
          (r) =>
            `- \`${r.problem.id}\` — the data has ${(r.problem.alternatives?.length ?? 0) + 1} rungs, the document has ${(r.problem.alternatives?.length ?? 0) + 1 + r.extra}`
        )
      : [`None.`]),
    ``,
    `## Every problem`,
    ``,
    `\`·\` means the section is present.`,
    ``,
    `| Problem | Pattern | Doc | ${SECTIONS.map((s) => s.heading.replace("The Overall ", "")).join(" | ")} |`,
    `|---|---|---|${SECTIONS.map(() => "---").join("|")}|`,
    ...rows.map((r) => {
      const cells = SECTIONS.map((s) => (r.missing.includes(s.key) ? "**no**" : "·"))
      return `| [${r.problem.id}](learn/${r.problem.id}.md) | ${r.problem.pattern} | ${r.taught ? "yes" : "**no**"} | ${cells.join(" | ")} |`
    }),
    ``,
  ]
  return lines.join("\n")
}

const rows = audit()
const untaught = rows.filter((r) => !r.taught).length
const undisclosed = rows.filter((r) => r.taught && r.extra > 0 && !r.disclosed).length

if (!quiet) {
  writeFileSync(REPORT, report(rows))
  console.log(`wrote ${REPORT}`)
  for (const s of SECTIONS) {
    const n = rows.filter((r) => r.missing.includes(s.key)).length
    console.log(`  ${String(n).padStart(3)} missing  ${s.heading}`)
  }
}

console.log(
  `${rows.length} problems · ${rows.length - untaught} taught · ${untaught} with no document · ` +
    `${undisclosed} adding approaches without saying so`
)

if (strict && undisclosed) {
  console.error(
    `\nFAIL: ${undisclosed} document(s) add an approach the data file does not have and never ` +
      `say it is an addition. docs/deep/README.md requires an added rung to be labelled.`
  )
  process.exit(1)
}
