// The authoring ledger: what every problem page still owes, one row each.
//
// `page-coverage.mjs` answers "how much of the corpus has field X" — a shape
// of the whole. This answers "what is left on problem Y", which is the view
// you cut a batch from. Both read the record; this one shares its rules with
// the BAND the reader sees (`src/lib/page-debt.ts`), so the page and the
// ledger cannot disagree about what is missing.
//
//   node scripts/page-backlog.mjs            # write docs/PAGE-BACKLOG.md
//   node scripts/page-backlog.mjs --check    # fail if that file is stale
//   node scripts/page-backlog.mjs --pattern trie
//
// IDEMPOTENT: running it twice writes the same bytes, so `--check` is a
// meaningful gate rather than a diff of timestamps. There is no date in the
// output for exactly that reason — the git log already carries when.
import { readFileSync, writeFileSync } from "node:fs"
import { PROBLEMS } from "../src/data/index.ts"
import { PATTERNS } from "../src/data/patterns.ts"
import { JOURNEY_CARDS } from "../src/engine/manifest.ts"
import { DEBT_IDS, debtsOf } from "../src/lib/page-debt.ts"
import { existsSync } from "node:fs"

const OUT = "docs/PAGE-BACKLOG.md"

const arg = (name) => {
  const i = process.argv.indexOf(name)
  return i === -1 ? undefined : process.argv[i + 1]
}

const hasJourney = new Set(JOURNEY_CARDS.map((c) => c.problemId).filter(Boolean))
/** a teaching document is either typed under src/problems/, or Markdown */
const hasDoc = (id) =>
  existsSync(`src/problems/${id}/doc.ts`) ||
  existsSync(`docs/deep/${id}_explained.md`)

function rows(only) {
  return PROBLEMS.filter((p) => !only || p.pattern === only).map((p) => {
    const debts = debtsOf(p, {
      journey: hasJourney.has(p.id),
      explanation: hasDoc(p.id),
    })
    return { p, owed: new Set(debts.map((d) => d.id)), count: debts.length }
  })
}

function render(only) {
  const all = rows(only)
  const total = all.length
  const clean = all.filter((r) => r.count === 0)
  const owedBy = Object.fromEntries(
    DEBT_IDS.map((id) => [id, all.filter((r) => r.owed.has(id)).length])
  )

  const lines = []
  lines.push("# Page backlog — what each problem page still owes")
  lines.push("")
  lines.push(
    "Generated by `node scripts/page-backlog.mjs`. **Do not edit by hand** — it is"
  )
  lines.push(
    "regenerated from the records, and `--check` fails the build when it is stale."
  )
  lines.push("")
  lines.push(
    "The rules are the ones the READER is shown at the foot of each page"
  )
  lines.push(
    "(`src/lib/page-debt.ts` → `components/problem-debt.tsx`), so this ledger and"
  )
  lines.push("the site cannot disagree about what is missing.")
  lines.push("")
  lines.push(`**${clean.length} of ${total} pages owe nothing.**`)
  lines.push("")
  lines.push("| Missing | Pages |")
  lines.push("|---|---|")
  for (const id of DEBT_IDS) {
    lines.push(`| \`${id}\` | ${owedBy[id]} |`)
  }
  lines.push("")
  lines.push("## Per problem")
  lines.push("")
  lines.push("`·` owes it. A blank cell is written.")
  lines.push("")
  lines.push(`| # | Problem | Pattern | ${DEBT_IDS.join(" | ")} | owed |`)
  lines.push(`|---|---|---|${DEBT_IDS.map(() => "---").join("|")}|---|`)
  // worst first: the thinnest pages are the ones a batch should start with
  const sorted = [...all].sort(
    (a, b) => b.count - a.count || a.p.id.localeCompare(b.p.id)
  )
  sorted.forEach((r, i) => {
    const cells = DEBT_IDS.map((id) => (r.owed.has(id) ? "·" : " "))
    const pattern =
      PATTERNS.find((x) => x.id === r.p.pattern)?.name ?? r.p.pattern
    // Link to where the record actually LIVES. 84 problems have a directory;
    // the rest are still one file under `src/data/problems/<pattern>/`, and a
    // ledger full of links to directories that do not exist is worse than one
    // with no links at all.
    const dir = `src/problems/${r.p.id}`
    const path = existsSync(dir)
      ? `../${dir}/`
      : `../src/data/problems/${r.p.pattern}/${r.p.id}.ts`
    lines.push(
      `| ${i + 1} | [${r.p.title}](${path}) | ${pattern} | ${cells.join(" | ")} | ${r.count} |`
    )
  })
  lines.push("")
  return lines.join("\n") + "\n"
}

const only = arg("--pattern")
const text = render(only)

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== text) {
    console.error(
      `\n  ${OUT} is stale. Run \`node scripts/page-backlog.mjs\` and commit it.\n`
    )
    process.exit(1)
  }
  console.log(`\n  ${OUT} is current.\n`)
} else if (only) {
  console.log(text)
} else {
  writeFileSync(OUT, text)
  console.log(`\n  wrote ${OUT}\n`)
}
